# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  victor_left_arm_joint_1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_arm_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_arm_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_arm_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_arm_joint_5:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_arm_joint_6:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_arm_joint_7:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerA_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerA_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerA_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerB_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerB_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerB_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerB_knuckle:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerC_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerC_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerC_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_left_gripper_fingerC_knuckle:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_5:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_6:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_arm_joint_7:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerA_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerA_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerA_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerB_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerB_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerB_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerB_knuckle:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerC_joint_2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerC_joint_3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerC_joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
  victor_right_gripper_fingerC_knuckle:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5