left_arm:
  kinematics_solver: victor_left_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.005
right_arm:
  kinematics_solver: victor_right_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.005
